name: Publish pokit

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Create .yarnrc.yml file
        run: |
          cat << EOF > .yarnrc.yml
          yarnPath: .yarn/releases/yarn-4.3.1.cjs
          nodeLinker: pnp
          enableGlobalCache: false
          npmScopes:
            pozalabs:
              npmRegistryServer: "https://npm.pkg.github.com"
              npmAlwaysAuth: true
              npmAuthToken: "${{ secrets.NPM_AUTH_TOKEN }}"
          EOF

      - name: Setup .npmrc file
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@POZAlabs'

      - name: Install packages
        run: yarn install

      - name: Build packages
        run: yarn run build

      - name: Publish library
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
